version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio-server
    ports:
      - "9000:9000"    
      - "9001:9001"    
    environment:
      MINIO_ROOT_USER: ${MINIO_USER_NAME}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - ./minio-data:/data 
    command: server /data --console-address ":9001"